mysql:
    dns: root:qinzhibao@tcp(127.0.0.1:3306)/ginChat?charset=utf8mb4&parseTime=True&loc=Local
redis:
    add: '127.0.0.1:6379'
    password: ''
    DB: 0
    poolSize: 30
    minIdleConn: 30
localAdd:
    ip: '192.168.5.2'
